using System;
using UniJSON;

namespace UniGLTF
{
    [Serializable]
    public class glTFAssets : IJsonSerializable
    {
        public string generator;

        [JsonSchema(Required = true, Pattern = "^[0-9]+\\.[0-9]+$")]
        public string version;

        public string copyright;

        [JsonSchema(Pattern = "^[0-9]+\\.[0-9]+$")]
        public string minVersion;

        // empty schemas
        public object extensions;
        public object extras;

        public string ToJson()
        {
            var f = new GLTFJsonFormatter();
            f.BeginMap();
            f.Key("generator"); f.Value(generator);
            f.Key("version"); f.Value(version);
            f.EndMap();
            return f.ToString();
        }

        public override string ToString()
        {
            return string.Format("GLTF-{0} generated by {1}", version, generator);
        }
    }
}
