using System;


namespace UniGLTF
{
    [Serializable]
    public class glTFAssets : IJsonSerializable
    {
        public string generator;
        public string version;
        public string copyright;
        public string minVersion;

        // empty schemas
        public object extensions;
        public object extras;

        public string ToJson()
        {
            var f = new JsonFormatter();
            f.BeginMap();
            f.Key("generator"); f.Value(generator);
            f.Key("version"); f.Value(version);
            f.EndMap();
            return f.ToString();
        }

        public override string ToString()
        {
            return string.Format("GLTF-{0} generated by {1}", version, generator);
        }
    }
}
